### ISSUE TITLE
AWS Secret for Kubeflow

### ISSUE THREAD

**Issue by strawberrypie** [provectus/swiss-army-kube#66]
Kubeflow Pipelines [allow](https://github.com/kubeflow/pipelines/blob/a3b60ba70cba176ec4bf815c98ad18f2640a6ba3/sdk/python/kfp/aws.py#L15) certain components to be able to access AWS resources using a secret that is defined in K8s. 
We need to create this secret for Kubeflow deployments. Below is a example that we previously used.
```yaml
---
apiVersion: v1
kind: Secret
metadata:
  annotations:
    aws.arn: arn:aws:iam::<ACCOUNT_ID_HERE>:user/<USER_HERE>
  name: aws-secret
  namespace: kubeflow
type: Opaque
data:
  AWS_ACCESS_KEY_ID: <KEY_HERE>
  AWS_SECRET_ACCESS_KEY: <ACCESS_KEY_HERE>
  ```
